// src/console/Frame.tsx
import { trace } from "tauri-plugin-log-api";
import "../globals.css";
import "./Frame.css";
import { useEffect, useState } from "react";

function Frame(props: { width?: string, height?: string, title?: string, visible?: boolean, className?: any, children?: any }) {
	const handleSize = 12;
	const [position, setPosition] = useState({ x: 0, y: 0, dx: 0, dy: 0, dragging: false });
	const [size, setSize] = useState({ width: "auto", height: "auto" });
	const [visible, setVisible] = useState(props.visible);

	function onMouseDown(event: React.MouseEvent<HTMLDivElement, MouseEvent>) {
		if (!visible) return;

		// @ts-ignore
		let target = event.target.dataset.target;

		if (target == "drag") {
			let dx = event.clientX - position.x;
			let dy = event.clientY - position.y;
			setPosition({ x: event.clientX - dx, y: event.clientY - dy, dx: dx, dy: dy, dragging: true });
		} else if (target == "close") {
			setVisible(false);
		}
	}

	function onMouseUp(event: React.MouseEvent<HTMLDivElement, MouseEvent>) {
		if (!position.dragging || !visible) return;
		setPosition({ x: event.clientX - position.dx, y: event.clientY - position.dy, dx: position.dx, dy: position.dy, dragging: false });
	}

	function onMouseMove(event: React.MouseEvent<HTMLDivElement, MouseEvent>) {
		if (!position.dragging || !visible) return;
		setPosition({ x: event.clientX - position.dx, y: event.clientY - position.dy, dx: position.dx, dy: position.dy, dragging: true });
	}

	useEffect(() => {
		if (visible) {
			trace((props.title || "Untitled") + ": showing frame");
		} else {
			trace((props.title || "Untitled") + ": hiding frame");
		}
	}, [visible]);

	useEffect(() => {
		if (position.dragging) {
			trace((props.title || "Untitled") + ": dragging frame");
		} else {
			trace((props.title || "Untitled") + ": stopped dragging frame");
		}
	}, [position.dragging]);

	return (
		<>
			{(visible) && (
				<div className={"frame " + props.className} style={{ width: size.width, height: size.height, left: position.x, top: position.y }} onMouseDown={onMouseDown} onMouseUp={onMouseUp} onMouseMove={onMouseMove}>
					<div className="title-bar">
						<img src="close.svg" data-target="close" className="handle close" style={{ width: handleSize + "px", height: handleSize + "px" }} draggable="false" />
						<img src="drag.svg" data-target="drag" className="handle drag" style={{ width: handleSize + "px", height: handleSize + "px" }} draggable="false" />
						{props.title || "Untitled"}
					</div>
					<div className="frame-body">
						{props.children}
					</div>
				</div>
			)}
		</>
	);
}

export default Frame;

// src/console/components/Frame.svelte
<script lang="ts">
	import "../../globals.css";
	import { trace } from "tauri-plugin-log-api";

	const handleSize = 12;

	export let title: string;
	export let width: number | string = "";
	export let height: number | string = "";
	export let left: number = 100;
	export let top: number = 100;
	export let visible: boolean = true;
	let dragging: boolean = false;

	function createUniqueId() {
		let id =
			Math.random().toString(36).substring(2, 15) +
			Math.random().toString(36).substring(2, 15);

		let element = document.getElementById(id);

		if (element) {
			return createUniqueId();
		}

		return id;
	}

	function close() {
		trace(title + ": closing.");
		visible = false;
	}

	function drag(event: MouseEvent) {
		trace(title + ": started dragging.");
		dragging = true;
	}

	function onMouseUp() {
		if (dragging) {
			trace(title + ": stopped dragging.");
			dragging = false;
		}
	}

	function onMouseMove(event: MouseEvent) {
		if (dragging) {
			left += event.movementX;
			top += event.movementY;
		}
	}
</script>

{#if visible}
	<div
		class="frame mono bg-black"
		style="width: {width}px; height: {height}px; left: {left}px; top: {top}px;"
		id={createUniqueId()}
	>
		<button class="title-bar none" on:mousedown={drag} on:dblclick={close}>
			<button class="none" on:click={close}>
				<img
					src="close.svg"
					data-target="close"
					class="handle close"
					draggable="false"
					alt="close"
					style="width: {handleSize}px; height: {handleSize}px;"
				/>
			</button>
			{title}
		</button>
		<div class="frame-body">
			<slot />
		</div>
	</div>
{/if}

<svelte:window on:mouseup={onMouseUp} on:mousemove={onMouseMove} />

<style>
	.frame {
		position: absolute;
		border: 1px solid var(--accent);
	}

	.frame-body {
		overflow: scroll;
	}

	.title-bar {
		display: flex;
		flex-direction: row;
		width: calc(100% - 20px);
		border-bottom: 1px solid var(--border);

		color: var(--accent);
		font: 900 16px var(--font-mono);
		padding-top: 10px;
		padding-left: 10px;
		padding-right: 10px;

		height: 24px;
		max-height: 24px;
	}

	.handle {
		padding-top: 2px;
		padding-right: 10px;
		margin: 0px;
		opacity: 0.5;
	}

	.handle:hover {
		opacity: 1;
	}

	.refresh {
		margin-left: auto;
	}
</style>
